name: Run Python Tests

on: push

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install apt prerequisites
      run: sudo apt-get install graphviz graphviz-dev
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run assignment 02 tests
      run: cd assignment-02; poetry run pytest -vv
    - name: Run project tests
      run: cd project; poetry run pytest -vv
